queans/main/urls.py
from django.urls import path
from main import views
urlpatterns=[
    path('',views.home,name='home'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('save-comment',views.save_comment,name='save-comment'),
    path('save-upvote',views.save_upvote,name='save-upvote'),
    path('save-downvote',views.save_downvote,name='save-downvote'),
    # User Register
    path('accounts/register/',views.register,name='register'),
    # Profile
    path('accounts/profile/',views.profile,name='profile'),
    # Ask QUestion
    path('ask-question',views.ask_form,name='ask-question'),
    # Tag Page
    path('tag/<str:tag>',views.tag,name='tag'),
    # Tags Page
    path('tags',views.tags,name='tags'),
]

queans/questans/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

queans/main/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser

# Custom User Model
class CustomUser(AbstractUser):
    bio=models.TextField()
    location=models.CharField(max_length=200)


# Question Model
class Question(models.Model):
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    detail=models.TextField()
    tags=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

# Answer Model
class Answer(models.Model):
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.detail

# Comment
class Comment(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='comment_user')
    comment=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

# UpVotes
class UpVote(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='upvote_user')

# DownVotes
class DownVote(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='downvote_user')

queans/main/forms.py
from django.forms import ModelForm
from .models import Answer,Question,CustomUser

class AnswerForm(ModelForm):
    class Meta:
        model=Answer
        fields=('detail')

class QuestionForm(ModelForm):
    class Meta:
        model=Question
        fields=('title','detail','tags')

class ProfileForm(ModelForm):
    class Meta:
        model=CustomUser
        fields=('first_name','last_name','username','bio','location')

queans/main/views.py
from django.shortcuts import render,HttpResponse
from django.http import JsonResponse
from .models import Question,Answer,Comment,UpVote,DownVote
from django.core.paginator import Paginator
from django.contrib import messages
from .forms import AnswerForm,QuestionForm,ProfileForm
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Count
# Home Page
def home(request):
    if 'q' in request.GET:
        q=request.GET['q']
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(title__icontains=q).order_by('-id')
    else:
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).all().order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'home.html',{'quests':quests})

# Detail
def detail(request,id):
    quest=Question.objects.get(pk=id)
    tags=quest.tags.split(',')
    answers=Answer.objects.filter(question=quest)
    answerform=AnswerForm
    if request.method=='POST':
        answerData=AnswerForm(request.POST)
        if answerData.is_valid():
            answer=answerData.save(commit=False)
            answer.question=quest
            answer.user=request.user
            answer.save()
            messages.success(request,'Answer has been submitted.')
    return render(request,'detail.html',{
        'quest':quest,
        'tags':tags,
        'answers':answers,
        'answerform':answerform
    })

# Save Comment
def save_comment(request):
    if request.method=='POST':
        comment=request.POST['comment']
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        Comment.objects.create(
            answer=answer,
            comment=comment,
            user=user
        )
        return JsonResponse({'bool':True})

# Save Upvote
def save_upvote(request):
    if request.method=='POST':
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=UpVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            UpVote.objects.create(
                answer=answer,
                user=user
            )
            return JsonResponse({'bool':True})

# Save Downvote
def save_downvote(request):
    if request.method=='POST':
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=DownVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            DownVote.objects.create(
                answer=answer,
                user=user
            )
            return JsonResponse({'bool':True})

# User Register
def register(request):
    form=UserCreationForm
    if request.method=='POST':
        regForm=UserCreationForm(request.POST)
        if regForm.is_valid():
            regForm.save()
            messages.success(request,'User has been registered!!')
    return render(request,'registration/register.html',{'form':form})

# Ask Form
def ask_form(request):
    form=QuestionForm
    if request.method=='POST':
        questForm=QuestionForm(request.POST)
        if questForm.is_valid():
            questForm=questForm.save(commit=False)
            questForm.user=request.user
            questForm.save()
            messages.success(request,'Question has been added.')
    return render(request,'ask-question.html',{'form':form})


# Questions according to tag
def tag(request,tag):
    quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(tags__icontains=tag).order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'tag.html',{'quests':quests,'tag':tag})

# Profile
def profile(request):
    quests=Question.objects.filter(user=request.user).order_by('-id')
    answers=Answer.objects.filter(user=request.user).order_by('-id')
    comments=Comment.objects.filter(user=request.user).order_by('-id')
    upvotes=UpVote.objects.filter(user=request.user).order_by('-id')
    downvotes=DownVote.objects.filter(user=request.user).order_by('-id')
    if request.method=='POST':
        profileForm=ProfileForm(request.POST,instance=request.user)
        if profileForm.is_valid():
            profileForm.save()
            messages.success(request,'Profile has been updated.')
    form=ProfileForm(instance=request.user)
    return render(request,'registration/profile.html',{
        'form':form,
        'quests':quests,
        'answers':answers,
        'comments':comments,
        'upvotes':upvotes,
        'downvotes':downvotes,
    })

# Tags Page
def tags(request):
    quests=Question.objects.all()
    tags=[]
    for quest in quests:
        qtags=[tag.strip() for tag in quest.tags.split(',')]
        for tag in qtags:
            if tag not in tags:
                tags.append(tag)
    # Fetch Questions
    tag_with_count=[]
    for tag in tags:
        tag_data={
            'name':tag,
            'count':Question.objects.filter(tags__icontains=tag).count()
        }
        tag_with_count.append(tag_data)
    return render(request,'tags.html',{'tags':tag_with_count})
        
        

queans/main/templates/ask-question.html
{% extends 'base.html' %}
{% block title %}Ask Question{% endblock %}
{% block content %}
<div class="container">
    <div class="card mt-5">
        <h5 class="card-header">Ask Question</h5>
        <div class="card-body">
            {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
            {% endfor %}
            <form method="post">
                {% csrf_token %}
                <table class="table table-bordered">
                    {{form.as_table}}
                    <tr>
                        <td colspan="2">
                            <button class="btn btn-primary">Submit</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}

queans/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Detail Page{% endblock %}</title>
    <!-- Animate 4 -->
    <link rel="stylesheet" href="{% static 'animate.min.css' %}" />
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <!-- Font Awesome 4 -->
    <link rel="stylesheet" href="{% static 'fa4/css/font-awesome.min.css' %}" />
    <!-- Jquery -->
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <!-- Bootstrap 4 Js -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">AskMe</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <form class="ml-auto" action="/">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search" />
                        <div class="input-group-append">
                        <button class="btn btn-success" type="submit" id="button-addon2">Search</button>
                        </div>
                    </div>
                </form>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/tags">Tags</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ask-question' %}">Ask</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/profile">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/register">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

queans/main/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{quest.title}}{% endblock %}
{% block content %}
<!-- Question List -->
    <div class="container">
        <h2 class="my-4">{{quest.title}}</h2>
        <p>{{quest.detail}}</p>
        <p>
            tags:
            {% for tag in tags %}
            <a href="/tag/{{tag|slugify}}" class="badge badge-secondary p-1">{{tag}}</a>
            {% endfor %}
        </p>
        <p>
            <span class="mr-4">{{quest.add_time|date:'d/m/Y'}}</span>
            <a href="#">{{quest.user.username}}</a>
        </p>
        <hr/>
        {% for answer in answers %}
        <div class="row">
            <div class="col-1" style="text-align: center;">
                <div class="upvote">
                    <strong class="upvote-count-{{answer.id}}">{{answer.upvote_set.count}}</strong><br/>
                    <span class="text-success">
                        <i class="fa fa-arrow-up fa-2x upvote-click" data-answer="{{answer.id}}"></i>
                    </span>
                </div>
                <div class="downvote mt-3">
                    <span class="text-danger">
                        <i class="fa fa-arrow-down fa-2x downvote-click" data-answer="{{answer.id}}"></i>
                    </span><br/>
                    <strong class="downvote-count-{{answer.id}}">{{answer.downvote_set.count}}</strong>
                </div>
            </div>
            <div class="col-11">
                <p>
                    {{ answer.detail }}
                </p>
                <p>
                    <a href="#" class="mr-3">{{answer.user.username}}</a>
                    <span class="mr-3"><span class="comment-count-{{answer.id}}">{{answer.comment_set.count}}</span> comments</span>
                    <span>{{answer.add_time|date:'d/m/Y h:i:s'}}</span>
                </p>
                <!-- Comment Section Start -->
                <h3 class="my-4">Comment</h3>
                <div class="comment-wrapper-{{answer.id}}">
                    {% for comment in answer.comment_set.all %}
                    <div class="card mb-2">
                        <div class="card-body">
                            <p>{{comment.comment}}</p>
                            <p>
                                <a href="#">{{comment.user.username}}</a>
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if user.is_authenticated %}
                <!-- Comment Form -->
                <div class="card my-3">
                    <h6 class="card-header">Add Comment</h6>
                    <div class="card-body">
                        <textarea class="form-control comment-text-{{answer.id}}"></textarea>
                        <button type="button" data-answer="{{answer.id}}" class="btn btn-dark my-3 save-comment">Submit</button>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <hr/>
        {% endfor %}

        {% if user.is_authenticated %}
        {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            <table class="table table-bordered">
                {{answerform.as_table}}
                <tr>
                    <td colspan="2">
                        <input type="submit" class="btn btn-dark" />
                    </td>
                </tr>
            </table>
        </form>
        {% endif %}
    </div>
<script>
    $(document).ready(function(){
        $(".save-comment").on('click',function(){
            var _answerid=$(this).data('answer');
            var _comment=$(".comment-text-"+_answerid).val();
            // Ajax
            $.ajax({
                url:"/save-comment",
                type:"post",
                data:{
                    comment:_comment,
                    answerid:_answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                beforeSend:function(){
                    $(".save-comment").addClass('disabled').text('saving...');
                },
                success:function(res){
                    if(res.bool==true){
                        $(".comment-text-"+_answerid).val('');
                        // Append Element
                        var _html='<div class="card mb-2 animate__animated animate__bounce">\
                        <div class="card-body">\
                            <p>'+_comment+'</p>\
                            <p>\
                                <a href="#">{{request.user}}</a>\
                            </p>\
                        </div>\
                    </div>';
                    $(".comment-wrapper-"+_answerid).append(_html);
                    var prevCount=$(".comment-count-"+_answerid).text();
                    $(".comment-count-"+_answerid).text(parseInt(prevCount)+1);
                    }
                    $(".save-comment").removeClass('disabled').text('Submit');
                }
            });
        });

        // Upvote
        $(".upvote-click").on('click',function(){
            var answerid=$(this).data('answer');
            // Ajax
            $.ajax({
                url:"/save-upvote",
                type:"post",
                data:{
                    answerid:answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                success:function(res){
                    var _prevupvote=$(".upvote-count-"+answerid).text();
                    if(res.bool==true){
                        $(".upvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                    }
                }
            });
        });

        // Downvote
        $(".downvote-click").on('click',function(){
            var answerid=$(this).data('answer');
            // Ajax
            $.ajax({
                url:"/save-downvote",
                type:"post",
                data:{
                    answerid:answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                success:function(res){
                    var _prevupvote=$(".downvote-count-"+answerid).text();
                    if(res.bool==true){
                        $(".downvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                    }
                }
            });
        });
    });
</script>
{% endblock %}

queans/main/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">AskMe</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/tags">Tags</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ask-question">Ask</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/profile">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/register">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Search Section -->
    <div class="container py-5">
        <div class="row">
            <div class="col-md-8 offset-2">
                <form>
                    <div class="input-group">
                        <input type="text" name="q" class="form-control form-control-lg" placeholder="Search" />
                        <div class="input-group-append">
                        <button class="btn btn-dark btn-lg" type="submit" id="button-addon2">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Question List -->

    

    <div class="container">
        {% for quest in quests %}
        <div class="card mb-4 shadow">
            <div class="card-body">
                <h4 class="card-title"><a href="/detail/{{quest.id}}">{{quest.title}}</a></h4>
                <p class="card-text">{{quest.detail}}</p>
                <p>
                    <a href="#" class="mr-2">{{quest.user.username}}</a>
                    <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                    <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
                </p>
            </div>
            <div class="card-footer">
                <small>{{quest.add_time}}</small>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if quests.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in quests.paginator.page_range %}
          {% if quests.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if quests.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
</body>
</html>

queans/main/templates/tag.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{tag}}{% endblock %}
{% block content %}
    <!-- Question List -->
    <div class="container py-5">
        {% for quest in quests %}
        <div class="card mb-3">
            <div class="card-body">
                <h4 class="card-title"><a href="/detail/{{quest.id}}">{{quest.title}}</a></h4>
                <p class="card-text">{{quest.detail}}</p>
                <p>
                    <a href="#" class="mr-2">{{quest.user.username}}</a>
                    <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                    <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if quests.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in quests.paginator.page_range %}
          {% if quests.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if quests.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
{% endblock %}

queans/main/templates/tags.html
{% extends 'base.html' %}
{% load static %}
{% block title %}All Tags{% endblock %}
{% block content %}
    <!-- Question List -->
    <div class="container py-5">
        <div class="row">
            {% for tag in tags %}
            <div class="col-2">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text"><a href="/tag/{{tag.name|slugify}}">{{tag.name}} 
                            <span class="badge badge-info">{{tag.count}}</span></a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}